import type { Metadata } from "next";
import "swiper/css";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Footer } from "@/components/Footer/Footer";
import { TanstackProvider } from "@/providers/tansteck-provider";
import CatalogModal from "@/components/CatalogModal/CatalogModal";
import { Suspense } from "react";
import type { LoadingSpinner } from "@/components/LoadingSpinner";
import Loading from "./loading";
import Navbar from "@/components/Navbar/Navbar";
import RegisterModal from "@/components/Modals/RegisterModal";
import LoginModal from "@/components/Modals/LoginModal";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-full`}
      >
        <TanstackProvider>
          <Navbar />
          <main className="flex-1 py-20 flex items-center justify-center">
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
          <Footer />
          <CatalogModal />
          <RegisterModal />
          <LoginModal />
        </TanstackProvider>
      </body>
    </html>
  );
}
